package solutions;

// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

public class prob12 {
	
	public static void main(String[] args) {
		System.out.println(firstTriangleNumberOverNDivisors(500));
	}
	
	public static int firstTriangleNumberOverNDivisors(int n) {
		int i = 1, triangleNumber = 1;
		while(numberOfDivisors(triangleNumber) <= n) {
			triangleNumber += ++i;
		}
		return triangleNumber;
	}
	
	public static int numberOfDivisors(int x) {
		int n = 2;
		int xHigher = x / 2;
		for (int i = 2; i <= xHigher; i++) {
			if (x % i == 0) {
				n += 1;
			}
		}
		return n;
	}
}
